cache:
  directories:
    - $HOME/.composer/cache

language: php

matrix:
  include:
    - php: 7.1
      env: LARAVEL='5.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*'
    - php: 7.3
      env: LARAVEL='5.8.*'
    - php: 7.3
      env: LARAVEL='6.*'
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" --no-interaction --no-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

before_script:
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - composer config discard-changes true

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
